# Generated by Django 3.1.2 on 2020-10-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(blank=True, choices=[('download', 'Download'), ('server', 'Server'), ('dw_sr', 'Download Server')], max_length=8, null=True),
        ),
    ]
