# Generated by Django 3.1.2 on 2020-10-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201008_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='season_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Season number'),
        ),
    ]
