# Generated by Django 3.1.2 on 2020-10-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201009_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default='slug', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', max_length=250),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(default='slug', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(default='slug', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='slug', max_length=250, unique=True),
        ),
    ]
