# Generated by Django 3.1.2 on 2020-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201009_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
