# Generated by Django 3.1.2 on 2020-12-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_link_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(blank=True, choices=[('download', 'Download'), ('server', 'Server')], max_length=8, null=True),
        ),
    ]
