# Generated by Django 3.1.2 on 2020-12-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201227_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ads',
            new_name='Adds',
        ),
    ]
